services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: directfunder
      POSTGRES_PASSWORD: directfunder
      POSTGRES_DB: directfunder
    ports:
      - "5432:5432"
    volumes:
      - direct-funder-db:/var/lib/postgresql/data

volumes:
  direct-funder-db:
